server:
  port: 8080

spring:
  application:
    name: seguro-veiculo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seguro-veiculo
      username: renanfretta
      password: Ren@nFretta1986