version: '3.3'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: renanfretta
      MONGO_INITDB_ROOT_PASSWORD: Ren@nFretta1986
    ports:
      - "27017:27017"
    networks:
      - seguro-veiculo-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: renanfretta
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ren@nFretta1986
    links:
      - mongo
    networks:
      - seguro-veiculo-network